### ISSUE TITLE
The term-id tag in the example is not the same as in the schema.

### ISSUE THREAD

**Issue by lennertVanSever** [erasmus-without-paper/ewp-specs-types-academic-term#4]
When I had a look at the [readme.md](https://github.com/erasmus-without-paper/ewp-specs-types-academic-term). I was happy to find a small example since it's easier to read than the [schema](https://github.com/erasmus-without-paper/ewp-specs-types-academic-term/blob/stable-v1/schema.xsd). 
Now my issue is that the schema names the term-id differently than in the example. 
In the example it says 
```
<ewp-id>2008/2009-2/2</ewp-id>
```
_I think this is very confusing since ``ewp-id`` doesn't mean much._
In the schema, the term id is defined as
```
 <xs:simpleType name="EwpAcademicTermId">
```
Objectively, ``EwpAcademicTermId`` says way more than  ``ewp-id`` so let's change the example to 
```
<ewp-academic-term-id>2008/2009-2/2</ewp-academic-term-id>
```

**Comment by kamil-olszewski-uw** [comment]
There is no incosistency. **EwpAcademicTermId** is the type. And **ewp-id** is the name of (sub)element of type **EwpAcademicTermId** inside element of type **AcademicTerm**. **EwpAcademicTermId** is not present in the example because types are not included in definitions of element instances.

We don't think name **ewp-id** is confusing. We have this subelement name in context of parent **AcademicTerm** type. There are subelements named **display-name** or **start-date** either and those names are understandable without any **academic-term-** prefix.

**Comment by wrygiel** [comment]
> I think this is very confusing since ewp-id doesn't mean much.

`ewp-id` doesn't mean much in itself, but note, that it is always used in context of academic term (`academic-term/ewp-id`). Thus, you should read it as "EWP identifier of an academic term".

Similarly, if in the future we needed to introduce some other identifier for academic terms, we would name them in similar fashion, e.g. `academic-term/eu-standard-id`.

**Comment by lennertVanSever** [comment]
It wasn't clear to me that the ewp-id is a subelement of the AcademicTerm but now I understand. Thanks for the fast replies.
