### ISSUE TITLE
Why include the academic year in the term-id?

### ISSUE THREAD

**Issue by lennertVanSever** [erasmus-without-paper/ewp-specs-types-academic-term#5]
I would like to suggest to remove the academic year from the term-id. Since the academic year is already defined in the ``academic-year-id``.  I think this could lead to confusion and I don't see any benefit.

**Comment by kamil-olszewski-uw** [comment]
There was no strong consensus on final form of type **EwpAcademicTermId**. We had to choose one of proposed solutions before the specification freeze. It is possible that we will return to discussion on this data type during/after some major update (maybe after June this year).

There are two important arguments for this form of the **EwpAcademicTermId**:

1. Element **academic-year-id** is now required inside type **AcademicTerm** because it was introduced in previous stable version. Element **ewp-id** is optional because at the moment of its introduction there was no certainty that every possible exotic academic term used somewhere in the world can be modeled using type **EwpAcademicTermId**. However, it is possible that in the future subelement **ewp-id** will become required and subelement **academic-year-id** will be deprecated or removed.

2. Type **EwpAcademicTermId** is used not only as subelement inside type **AcademicTerm**. It is possible that it will be used in some API or data type where subelement of type **AcademicYearId** will not be present.
