### ISSUE TITLE
Adding validation standards

### ISSUE THREAD

**Issue by lennertVanSever** [erasmus-without-paper/ewp-specs-types-academic-term#7]
Would it be smart to suggest the following validation rules in the documentation?

- The start date should be earlier than the end date
- The other suggestions are based on the values from issue #6 
- Application/nomination deadline should be earlier than the begin date
- Application deadline should be earlier than the nomination deadline 
- The arrival date should be earlier than the end date
- Start exam date should be earlier than the end date

Other proposals are always welcome of course.

**Comment by MartaJuzepczuk** [comment]
In the documentation of other APIs we don't write such intuitive rules. For some fields there are some rules present, but they usually explain some unobvious issues, for example:

> This ID should be provided by the server ONLY if it implements EWP's Interinstitutional Agreements API.

> If provided, then it MUST have the value of the "official" ounit-id

These rules would be less visible if they were mixed with lots of other rules such as "the start is before the end". And since this dates and all the other fields should be the **real** mobilities data, they will meet all such requirements as a consequence.
